#!/bin/bash
printf -v date_time '%(%Y-%m-%d %X)T';
if [ -d "/sys/class/power_supply/BAT0" ]; then
    battery_capacity=$(cat /sys/class/power_supply/BAT0/capacity)
    battery_status=$(cat /sys/class/power_supply/BAT0/status)
    echo "$battery_status $battery_capacity% | $date_time";
else
    echo "$date_time";
fi
